version: 2
project_name: httpprobe

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    binary: httpprobe
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w -X github.com/mrfoh/httpprobe/cmd/httpprobe.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Scoop bucket integration
scoops:
  - name: httpprobe
    description: "A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON"
    homepage: "https://github.com/mrfoh/httpprobe"
    license: "MIT"
    repository:
      owner: mrfoh
      name: scoopbucket
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: GitHub Actions Bot
      email: github-actions[bot]@users.noreply.github.com
    commit_msg_template: "chore: update httpprobe manifest to {{ .Tag }} [skip ci]"
    directory: bucket

# Homebrew tap integration
brews:
  - name: httpprobe
    description: "A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON"
    homepage: "https://github.com/mrfoh/httpprobe"
    license: "MIT"
    repository:
      owner: mrfoh
      name: homebrewtap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: GitHub Actions Bot
      email: github-actions[bot]@users.noreply.github.com
    commit_msg_template: "chore: update httpprobe formula to {{ .Tag }} [skip ci]"
    directory: Formula
    install: |
      bin.install "httpprobe"
    test: |
      system "#{bin}/httpprobe", "version"

snapcrafts:
  - id: httpprobe
    name: httpprobe
    publish: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    summary: A powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON
    description: |
      httpprobe is a powerful HTTP API testing tool for defining, running, and validating API tests using YAML or JSON.
    grade: stable
    confinement: strict
    license: MIT
    base: core20
    apps:
      probe:
        command: httpprobe
        plugs: [ "home", "network" ]
        aliases: [ "httprobe" ]