name: httpprobe
version: git
summary: HTTP API testing tool
description: |
  A powerful HTTP API testing tool for defining, running, 
  and validating API tests using YAML or JSON test definitions.

base: core22
grade: stable
confinement: strict

parts:
  httpprobe:
    plugin: go
    source: .
    go-buildtags: [static]
    build-environment:
      - CGO_ENABLED: "0"
    override-build: |
      go build -o $SNAPCRAFT_PART_INSTALL/bin/httpprobe ./cmd/main.go

apps:
  httpprobe:
    command: bin/httpprobe
    plugs:
      - network
      - home