name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Run tests
        run: make test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          
      # Set up Snapcraft
      - name: Set up Snapcraft
        uses: snapcore/action-build@v1
        if: startsWith(github.ref, 'refs/tags/')
          
      # Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          # Used for GitHub token and pushing to other repos
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}