name: Update Scoop Manifest

on:
  release:
    types: [published]

jobs:
  update-scoop-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "Version: ${GITHUB_REF#refs/tags/v}"

      - name: Update scoop manifest
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          
          # Update version in manifest
          jq '.version = env.VERSION' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          # Update URLs in manifest
          jq '.architecture."64bit".url = "https://github.com/mrfoh/httpprobe/releases/download/v" + env.VERSION + "/httpprobe-v" + env.VERSION + "_windows_amd64.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq '.architecture."32bit".url = "https://github.com/mrfoh/httpprobe/releases/download/v" + env.VERSION + "/httpprobe-v" + env.VERSION + "_windows_386.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq '.architecture."arm64".url = "https://github.com/mrfoh/httpprobe/releases/download/v" + env.VERSION + "/httpprobe-v" + env.VERSION + "_windows_arm64.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          # Update autoupdate URLs
          jq '.autoupdate.architecture."64bit".url = "https://github.com/mrfoh/httpprobe/releases/download/v$version/httpprobe-v$version_windows_amd64.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq '.autoupdate.architecture."32bit".url = "https://github.com/mrfoh/httpprobe/releases/download/v$version/httpprobe-v$version_windows_386.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq '.autoupdate.architecture."arm64".url = "https://github.com/mrfoh/httpprobe/releases/download/v$version/httpprobe-v$version_windows_arm64.tar.gz"' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json

      - name: Download release assets to compute hashes
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          mkdir -p tmp
          
          # Download assets
          curl -L "https://github.com/mrfoh/httpprobe/releases/download/v${VERSION}/httpprobe-v${VERSION}_windows_amd64.tar.gz" -o tmp/httpprobe-v${VERSION}_windows_amd64.tar.gz
          curl -L "https://github.com/mrfoh/httpprobe/releases/download/v${VERSION}/httpprobe-v${VERSION}_windows_386.tar.gz" -o tmp/httpprobe-v${VERSION}_windows_386.tar.gz
          curl -L "https://github.com/mrfoh/httpprobe/releases/download/v${VERSION}/httpprobe-v${VERSION}_windows_arm64.tar.gz" -o tmp/httpprobe-v${VERSION}_windows_arm64.tar.gz
          
          # Compute SHA256 hashes
          AMD64_HASH=$(sha256sum tmp/httpprobe-v${VERSION}_windows_amd64.tar.gz | cut -d ' ' -f 1)
          I386_HASH=$(sha256sum tmp/httpprobe-v${VERSION}_windows_386.tar.gz | cut -d ' ' -f 1)
          ARM64_HASH=$(sha256sum tmp/httpprobe-v${VERSION}_windows_arm64.tar.gz | cut -d ' ' -f 1)
          
          # Update hashes in manifest
          jq --arg hash "$AMD64_HASH" '.architecture."64bit".hash = $hash' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq --arg hash "$I386_HASH" '.architecture."32bit".hash = $hash' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json
          
          jq --arg hash "$ARM64_HASH" '.architecture."arm64".hash = $hash' bucket/httpprobe.json > bucket/httpprobe.json.tmp
          mv bucket/httpprobe.json.tmp bucket/httpprobe.json

      - name: Commit and push updated manifest
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add bucket/httpprobe.json
          git commit -m "chore: update scoop manifest for v${{ steps.get_version.outputs.version }}"
          git push